# parameters file for WM9 4 weeks drug 20150701

load_WM9_4weeks_20150701 <- function(){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_4weeks_20150701'
  
  # Load data 
  data <- read.csv('dentistData/WM9_4weeks_20150701.txt')
  
  # Load thresholds 
  thresholds <- data.frame(geneName=c('EGFR','SOX10','CCNA2','GAPDH','WNT5A','PDGFRB',
                                          'PDGFC','SERPINE1','NGFR','NRG1','FOSL1',
                                          'VEGFC','AXL','MITF','LOXL2','RUNX2','FGFR1',
                                          'JUN','VGF'),threshold=c(10, #EGFR
                                                                   150, #Sox10
                                                                   10, #CCNA2
                                                                   1000, #gapdh
                                                                   10, #WNT5A
                                                                   10, #PDGFRB
                                                                   10, #PDGFC
                                                                   100, #serpine1
                                                                   20, #ngfr
                                                                   20, #nrg1
                                                                   5, #fosl1
                                                                   10, #vegfc
                                                                   40, #axl
                                                                   120, #mitf
                                                                   50, #loxl2
                                                                   10, #runx2
                                                                   20, #fgfr1
                                                                   20, #jun
                                                                   20)) #vgf
  # These were selected based upon the commented plot
  # ggplot(data,aes(x=SOX10))+geom_histogram() 
  # ggplot(data,aes(x=GAPDH))+geom_histogram() 
  # ggplot(data,aes(x=CCNA2))+geom_histogram() + geom_vline(xintercept=25)
  # ggplot(data,aes(x=MITF))+geom_histogram() + geom_vline(xintercept=90)

  
  WM9_4weeks_20150701 <- list(plotName,plotDir,data,thresholds)
  return(WM9_4weeks_20150701)
}

load_WM9_4weeks_20150701_colonyAnnotations <- function(){
  plotDir <- '/Users/paudelbb/Downloads/'
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_4weeks_20150701'
  
  # Load data 
  data <- read.csv('/Users/paudelbb/Downloads/dentistData/WM9_4weeks_20150701_clusterAnnotations.txt')
  
  # Load thresholds 
  thresholds <- data.frame(geneName=c('EGFR','SOX10','CCNA2','GAPDH','WNT5A','PDGFRB',
                                      'PDGFC','SERPINE1','NGFR','NRG1','FOSL1',
                                      'VEGFC','AXL','MITF','LOXL2','RUNX2','FGFR1',
                                      'JUN','VGF'),threshold=c(10, #EGFR
                                                               150, #Sox10
                                                               10, #CCNA2
                                                               1000, #gapdh
                                                               10, #WNT5A
                                                               10, #PDGFRB
                                                               10, #PDGFC
                                                               100, #serpine1
                                                               20, #ngfr
                                                               20, #nrg1
                                                               5, #fosl1
                                                               10, #vegfc
                                                               40, #axl
                                                               120, #mitf
                                                               50, #loxl2
                                                               10, #runx2
                                                               20, #fgfr1
                                                               20, #jun
                                                               20)) #vgf
  # These were selected based upon the commented plot
  # ggplot(data,aes(x=SOX10))+geom_histogram() 
  # ggplot(data,aes(x=GAPDH))+geom_histogram() 
  # ggplot(data,aes(x=CCNA2))+geom_histogram() + geom_vline(xintercept=25)
  # ggplot(data,aes(x=MITF))+geom_histogram() + geom_vline(xintercept=90)
  
  
  WM9_4weeks_20150701 <- list(plotName,plotDir,data,thresholds)
  return(WM9_4weeks_20150701)
}

