# parameters file for WM9 1week 20150715
# cleaned by Maggie

load_WM9_1week_20150715 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_1week_20150715_'
  
  # Load data 
  data <- read.csv('dentistData/WM9_1week_20150715.txt')
  #gapdhNormData <- gapdhNormalizeData(data, minGapdh=50)
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(data)[4:22],
                                  threshold=c(10,#EGFR
                                              0,#SOX10 - threshold anywhere
                                              100,#CCNA2 - no spots
                                              0,#GAPDH - threshold anywhere
                                              29,#WNT5A--seems a bit high (maybe threshold lower)
                                              21,#PDGFRB
                                              100,#PDGFC - no spots
                                              20,#SERPINE1
                                              38,#NGFR
                                              21,#NRG1 
                                              100,#FOSL1 - no spots
                                              21,#VEGFC 
                                              41,#AXL
                                              10,#MITF - threshold anywhere
                                              24,#LOXL2
                                              5,#RUNX2 - should have spots
                                              20,#FGFR1 - no spots
                                              8,#JUN
                                              100)) #VGF - no spots
  
  thresholds <- data.frame(geneName=colnames(data)[4:22],threshold=rep(0,19))
  #gapdhThresholds <- data.frame(geneName=colnames(data)[4:22],
  #threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(data[,i+3],1-percentileForThresholds)
    #gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {thresholds$threshold[i] <- percentThresh} 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  
  
  #WM9_48hrs_20150624 <- list(plotName,plotDir,data,thresholds, gapdhThresholds)
  WM9_1week_20150715 <- list(plotName,plotDir,data,thresholds)
  return(WM9_1week_20150715)
}

## Maggie's notes
# 20150716_WM9_A6_G3_week1_take2
# Hyb 1 
# Alexa- cleaned down to 10, minimum threshold = 10
# Cy - no legit spots, changed thresholds 
# NIR -  loks good, some spots under called. Checked down to 200-something. Threshold anywhere. 
# tmr - checked down to 140 , spots look pretty good. Can probably threshold anywhere. 
# Hyb 2
# alexa - min thresh = 29
# Cy - changed thresholds, no legit spots
# NIR- checked down to 20, nothing legit except the top cell. Threshold = 223 which is legit and probably actually more spots than that. 
# TMR- threshold= 21 (Cells with 55 and 21 is actually 1 cell called as 2, cell with 24 is actually 2 cells called as 1) Checked down to 10, nothing below 21 is legit spots.
# 
# Hyb 3
# Alexa-  threshold = 38(changed threshold) Checked down to 13, nothing below 38 is legit. 
# Cy - no legit spots, threshold changed
# NIR - threshold = 21, checked down to 16, everything below 21 not legit. 
# tmr - threshold = 21, checked down to 8, everything below 21 not legit. 
# Hyb 4
# Alexa - Threshold = 41, checked down to 10, nothing legit below 41.
# cy- changed threshold, no legit spots
# nir - cleaned down through 5 spots, don’t threshold below 5. 
# tmr- checked down to 42, looks good, can probably threshold anywhere.
# Hyb 5
# Alexa - cleaned down to 20. don’t thresh below 20
# Cy - no legit spots
# tmr - Changed threshold.  Overall quality poor. Some cells have legit spots, but trying to set the threshold to capture them gets a ton of hazy background. I have get fewer spots than there actually are to avoid having to delete many, many cells where it’s just background. Cleaned to 8, don’t threshold below that. 

