# parameters file for WM9 colonies 6/24/15
# Notes - no signal in FOSL1 FGFR1 LOXL2 PDGFC and RUNX2.... yikes.

load_WM9_colonies_20150624 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_colonies_20150624_'
  
  # Load data 
  colonyData <- read.csv('dentistData/WM9_colonies_20150624.txt')
  gapdhNormData <- gapdhNormalizeData(colonyData, minGapdh=50)
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(colonyData)[4:22],
                                  threshold=c(10,20,5,20,10,10,10,25,10,50,10,10,10,10,10,10,20,15,10))
  # I updated these based upon Maggie's notes from cleaning.
  # no signal in FOSL1 and FGFR1
  
  thresholds <- data.frame(geneName=colnames(colonyData)[4:22],
                           threshold=rep(0,19))
  gapdhThresholds <- data.frame(geneName=colnames(colonyData)[4:22],
                                threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(colonyData[,i+3],1-percentileForThresholds)
    gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {
      thresholds$threshold[i] <- percentThresh
    } 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  # For the non-jackpot genes, I want to override the percentiles and set a manual threshold - 
  # We just want to pick something that will give us all the "high" cells:
  
  # These were selected based upon the commented plot
  # ggplot(colonyData,aes(x=SOX10))+geom_histogram() + geom_vline(xintercept=150)
  thresholds$threshold[2] <- 150 #SOX10
  #ggplot(colonyData,aes(x=GAPDH))+geom_histogram() + geom_vline(xintercept=600)
  thresholds$threshold[4] <- 500 #GAPDH
  
  
  #percentileForThresholds <- 0.02
  #ggplot(gapdhNormData,aes(x=MITF))+geom_histogram() + 
  #  geom_vline(xintercept=quantile(gapdhNormData$MITF,1-percentileForThresholds))
  
  gapdhThresholds$threshold[3] <- 1 # CCNA2
  gapdhThresholds$threshold[7] <- 1 # PDGFC - no signal
  gapdhThresholds$threshold[11] <- 1 # FOSL1 - no signal
  gapdhThresholds$threshold[15] <- 1 # LOXL2 - no signal
  gapdhThresholds$threshold[16] <- 1 # RUNX2 - no signal
  gapdhThresholds$threshold[17] <- 1 # FGFR1 - no signal
  #thresholds$gapdhThreshold[]
  
  WM9_colonies_20151006 <- list(plotName,plotDir,colonyData,thresholds,gapdhThresholds)
  return(WM9_colonies_20151006)
  
}


# notes from the google docs
# processed by Maggie
# Data from 2015/06/24
# hyb 1:
#   EGFR threshold cannot be set lower than 10.
# CCNA2 signal is crappy… questionable if it worked and/or if these cells are just all cell cycle arrested. Many cells have just 1 spot (often in the nucleus) - threshold needs to be >= 5.
# 
# hyb 2:
#   WNT5A Alexa594 --> threshold cannot be set lower than 10… data cleaned down to 10
# PDGFC Atto647n → did not find any real signal here, do not set threshold above 10
# PDGFRB Cy3 - clean through 10, set threshold less than 10….found some nice signal, many of the high cells are in small clusters
# SERPINE1 - clean up through 25 
# --this gene had a dense region in the upper middle of the scan that has a lot of spurious autofluorescence. 
# 
# hyb 3:
#   NGFR is pretty clean
# FOSL1 does not have any real signal…
# VEGFC has real spots at 25, 17, 16…., do not set threshold <=10
# FOSL1 did not find any real spots, do not set threshold <= 6
# 
# hyb 4:
#   AXL is cleaned down to 10, do not set threshold <=10
# MITF is fine, set threshold anywhere
# LOXL2 does not have any real simple, do not set threshold <=8
# RUNX2 does not have any real simple, do not set threshold <=9
# 
# hyb5:
#   FGFR1 - nothing
# JUN - has nice real signal.do not set threshold < 15



