# parameters file for primary melanocytes 20150717

load_primaryMelano_20150717 <- function(){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'primaryMelano_20150717_'
  
  # Load data 
  data <- read.csv('dentistData/primaryMelanocytes_20150717.txt')
  
  # Load thresholds 
  thresholds <- data.frame(geneName=c('EGFR','SOX10','CCNA2','GAPDH','WNT5A','PDGFRB',
                                      'PDGFC','SERPINE1','NGFR','NRG1','FOSL1',
                                      'VEGFC','AXL','MITF','LOXL2','RUNX2','FGFR1',
                                      'JUN','VGF'),threshold=c(5, #EGFR - no expression
                                                               150, #Sox10
                                                               10, #CCNA2
                                                               500, #gapdh
                                                               10, #WNT5A - no expression 
                                                               10, #PDGFRB - no expression
                                                               10, #PDGFC - no expression
                                                               7, #serpine1 - expressed
                                                               40, #ngfr - expressed
                                                               10, #nrg1 - no expression
                                                               5, #fosl1 - no expression
                                                               10, #vegfc - no expression
                                                               15, #axl - expressed
                                                               75, #mitf - expressed
                                                               10, #loxl2 - no expression
                                                               10, #runx2 - no expression
                                                               26, #fgfr1 - expressed
                                                               10, #jun - no expression
                                                               20)) #vgf - no expression
  # These were selected based upon the commented plot
  # ggplot(data,aes(x=SOX10))+geom_histogram() 
  # ggplot(data,aes(x=GAPDH))+geom_histogram() 
  # ggplot(data,aes(x=CCNA2))+geom_histogram() + geom_vline(xintercept=25)
  # ggplot(data,aes(x=MITF))+geom_histogram() + geom_vline(xintercept=90)
  
  
  WM9_4weeks_20150701 <- list(plotName,plotDir,data,thresholds)
  return(WM9_4weeks_20150701)
}


# # notes from the google doc
# Maggie- Primary melanocytes
# Hyb1:
#   EGFR - cleaned down to threshold 2, don’t threshold lower
# SOX10 - signal good, threshold anywhere
# CCNA2- cleaned down to 10, threshold a little low, spots under called in some cells, but that mostly avoids calling spots where there aren’t any.
# GAPDH - just spot checked but for the most part signal looks good. Didn’t change threshold or anything. 
# 
# Hyb2:
#   WNT5a - cleaned down to 3 spots, basically everything was junk. Haven’t seen any legit spots yet. Then I gave up and quit cause it was taking too long to just delete little bits of crap. 
# PDGFC - cleaned down to 3 spots, basically everything was junk. Haven’t seen any legit spots yet. Then I gave up and quit cause it was taking too long to just delete little bits of crap. 
# SERPINE1 - Cleaned down through 6 spots per cell. Some of the 6 spot cells are a little iffy. 
# PDGFRB- cleaned down to 2 spots. Didn’t see any signal, just junk
# 
# Hyb 3: Had some ignoring nir_sac... error, but otherwise DENTIST loaded ok. I’m guessing those were duplicate files?
# NGFR - Threshold is missing some spots but I didn’t want to move it too high. Checked through 50 spots and only one spot was bad. The signal looks pretty good. 
# FOSL1 - Cleaned down to 4 spots. Everything seems to be Fluorescent Crap Stuck to the SlideTM   Haven’t seen legit spots
# VEGFC-  Cleaned down to 3 spots. Don’t see anything that looks real.
# NRG1- Cleaned down to 3 spots. Don’t see anything that looks real.
# 
# Hyb 4: 
#   AXL - Cleaned down through 20. Can go lower if need be.  Most cells are clean but around 21-19 started getting a few that were junk. 
# LOXL2 - Cleaned down to 5, only see junk, not real spots. 
# RUNX2- Cleaned down to 4, didn’t see any legit spots. 
# MITF - Checked all cells down through 80 spots. Only cleaned 1 cell. Spot checked down to 50 spots. Signal looks good. I think you can set the threshold anywhere. 
# 
# Hyb 5:
#   EGFR1 - Cleaned through 25. Having 2 cells counted as one seems to happen more frequently around 25 spots too for some reason. Don’t threshold lower than 25 but 26 is safer.
# VGF- cleaned down to 2, no real spots.
# JUN - no spots. cleaned down to 0


