# parameters file for WM9 no drug 20150810

load_WM983b_noDrug_20150525 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM983b_noDrug_20150525_'
  
  # Load data 
  noDrugData <- read.csv('dentistData/WM983b_noDrug_20150525.txt')
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(noDrugData)[4:22],
                                  threshold=c(10,0,0,0,0,10,10,100,0,0,10,10,0,0,40,15,20,20,100))
  
  thresholds <- data.frame(geneName=colnames(noDrugData)[4:22],
                           threshold=rep(0,19))

  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(noDrugData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {
      thresholds$threshold[i] <- percentThresh
      } 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  # For the non-jackpot genes, I want to override the percentiles and set a manual threshold - 
  # We just want to pick something that will give us all the "high" cells:
  
  # These were selected based upon the commented plot
  # ggplot(noDrugData,aes(x=SOX10))+geom_histogram() + geom_vline(xintercept=200)
  #thresholds$threshold[2] <- 150 #SOX10
  #ggplot(noDrugData,aes(x=GAPDH))+geom_histogram() + geom_vline(xintercept=750)
  #thresholds$threshold[4] <- 750 #GAPDH
  #ggplot(noDrugData,aes(x=CCNA2))+geom_histogram() + geom_vline(xintercept=25)
  #thresholds$threshold[3] <- 25
  #ggplot(noDrugData,aes(x=MITF))+geom_histogram() + geom_vline(xintercept=90)
  #thresholds$threshold[14] <- 120
  
  
  #percentileForThresholds <- 0.02
  #ggplot(gapdhNormData,aes(x=MITF))+geom_histogram() + 
  #  geom_vline(xintercept=quantile(gapdhNormData$MITF,1-percentileForThresholds))
  

  #thresholds$gapdhThreshold[]
  
  WM983b_noDrug_20150525<- list(plotName,plotDir,noDrugData,thresholds)
  return(WM983b_noDrug_20150525)
  
}


# ## My notes:
# 20150525_wm983b_E9_G5_NoDrug_pool1_hyb1 -- note the gene list is different from WM9 in WM983b 
# hyb1
# EGFR A594 - nothing, set threshold at 10
# SOX10 Cy3 - looks fine, threshold anywhere
# GAPDH Atto700 - looks fine, threshold anywhere
# CCNA2 Atto647n - looks fine, threshold anywhere
# 
# hyb2
# CYR61 A594 - looks fine, threshold anywhere
# PDGFRB Cy3 - nothing, set threshold at 10
# SERPINE1 Atto700 - weird data set because I think the cells with the highest number of spots are real, but can’t say about  -- I think this data may have the old nir problem.
# POSTN Atto647n - nothing, set threshold at 10
# 
# hyb3
# NRG1 Cy3 - looks fine, threshold anywhere
# WNT5A+UTR Atto647n - nothing, threshold at 10
# VEGFC Atto700 - nothing threshold at 10
# NGFR Alexa594 - looks fine, threshold anywhere
# 
# hyb4 -- scan may have gone out of focus in upper righthand corner.
# RUNX2 Atto700 - cleaned down through 15
# EPHA2 - Cy3 - looks fine, threshold anywher
# AXL - A594 - looks fine, threshold anywhere
# LOXL2 - Atto647n - cleaned down through 40
# 
# hyb5
# FGFR1  Alexa594 - cleaned down through 40, but it was not in bad shape, could threshold lower probably
# JUN Cy3 - cleaned down through 40, but pretty clean and could be thresholded lower.
# VGF Atto647n - impossible to threshold correctly, not usable.
