# parameters file for WM9 no drug 20150618


load_WM9_noDrug_20150618 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir

  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_noDrug_20150618_'

  # Load data
  noDrugData <- read.csv('dentistData/WM9_noDrug_20150618.txt')
  gapdhNormData <- gapdhNormalizeData(noDrugData, minGapdh=50)

  # Load thresholds
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(noDrugData)[4:22],
                                  threshold=c(10,20,20,20,15,5,10,20,20,10,10,10,10,10,10,10,5,10,10))

  thresholds <- data.frame(geneName=colnames(noDrugData)[4:22],threshold=rep(0,19))
  gapdhThresholds <- data.frame(geneName=colnames(noDrugData)[4:22],
                                threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(noDrugData[,i+3],1-percentileForThresholds)
    gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {thresholds$threshold[i] <- percentThresh}
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }


  gapdhThresholds$threshold[7] <- 1  #this is PDGFC, which had no positive cells
  gapdhThresholds$threshold[11] <- 1 #this is FOSL1, which also had no positive cells
  gapdhThresholds$threshold[16] <- 1 #RUNX2
  gapdhThresholds$threshold[19] <- 1
  gapdhThresholds$threshold[17] <- 0.025 #FGFR1
  gapdhThresholds$threshold[1] <- 0.05

  # For the non-jackpot genes, I want to override the percentiles and set a manual threshold -
  # We just want to pick something that will give us all the "high" cells:

  # These were selected based upon the commented plot
  # ggplot(noDrugData,aes(x=SOX10))+geom_histogram() + geom_vline(xintercept=350)
  thresholds$threshold[2] <- 350 #SOX10
  #ggplot(noDrugData,aes(x=GAPDH))+geom_histogram() + geom_vline(xintercept=500)
  thresholds$threshold[4] <- 500 #GAPDH
  #ggplot(noDrugData,aes(x=CCNA2))+geom_histogram() + geom_vline(xintercept=50)
  thresholds$threshold[3] <- 50
  #ggplot(noDrugData,aes(x=MITF))+geom_histogram() + geom_vline(xintercept=90)
  thresholds$threshold[14] <- 90

  WM9_noDrug_20150618 <- list(plotName,plotDir,noDrugData,thresholds, gapdhThresholds)
  return(WM9_noDrug_20150618)
}

