# parameters file for WM9 48 hours 20150624
# cleaned by Maggie

load_WM9_48hrs_20150624 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_48hrs_20150624_'
  
  # Load data 
  data <- read.csv('dentistData/WM9_48hrs_20150624.txt')
  #gapdhNormData <- gapdhNormalizeData(data, minGapdh=50)
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(data)[4:22],
                                  threshold=c(5,#EGFR
                                              0,#SOX10 - threshold anywhere
                                              100,#CCNA2 - no spots
                                              0,#GAPDH - threshold anywhere
                                              7,#WNT5A
                                              10,#PDGFRB
                                              100,#PDGFC - no spots
                                              22,#SERPINE1
                                              30,#NGFR
                                              100,#NRG1 - no spots
                                              100,#FOSL1 - no spots
                                              14,#VEGFC - should have spots
                                              16,#AXL
                                              10,#MITF - threshold anywhere
                                              24,#LOXL2
                                              11,#RUNX2 - should have spots
                                              100,#FGFR1 - no spots
                                              20,#JUN
                                              100)) #VGF - no spots
  
  thresholds <- data.frame(geneName=colnames(data)[4:22],threshold=rep(0,19))
  #gapdhThresholds <- data.frame(geneName=colnames(data)[4:22],
                                #threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(data[,i+3],1-percentileForThresholds)
    #gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {thresholds$threshold[i] <- percentThresh} 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  
  
  #WM9_48hrs_20150624 <- list(plotName,plotDir,data,thresholds, gapdhThresholds)
  WM9_48hrs_20150624 <- list(plotName,plotDir,data,thresholds)
  return(WM9_48hrs_20150624)
}

## Maggie's notes
# Hyb 1:
#   Alexa - cleaned down through 5 spots. Don’t threshold below 5. Accidently changed threshold, then changed it back as close as possible and rechecked. Still the same cells/spots.
# Cy - changed threshold, no legit spots.
# Nir- checked down to 650, all spots look good except where multiple cells together. threshold anywhere. 
# tmr - changed thresholds, checked down to 250, all good, threshold anywhere
# 
# Hyb 2: 
#   Alexa - cleaned down to 7, minimum threshold =7
# Cy - No legit spots.
# NIR- cleaned down to 22, minimum threshold = 22 hard to tell on threshold whether it is messy or out of focus legit spots
# TMR - cleaned down to 10.  Some of the 9 spot cells are legit, but most are fuzzy background. Minimum thresh = 10
# 
# Hyb 3:
#   Alexa- Reset thresh. Cleaned down to 30. SOme cells have a few more spots than called but for the most part it looks good. Minimum thresh = 30. 
# Cy- No legit spots. 
# Nir- max thresh = 14, below that is mostly junk, maybe some legit stuff. 
# tmr - changed threshold, no legit spots
# Hyb 4
# Alexa- cleaned down to 16. Max thresh = 16
# Cy - min thresh = 24
# nir - min thresh = 11
# tmr- hard to tell, transcription sites are bright and mess up contrast. mainly going off of spot distribution, checked down to 100 but most cells are good. Biggest problem is clumps of cells, so you could probably go lower. 
# Hyb5
# Alexa - no legit spots, chnaged thresholds
# Cy - changed thresholds, no legit spots
# tmr - cleaned down to 20, minimum thresh = 20

