# parameters file for WM9 colonies 1/26/2016


load_WM9_colonies_20160126 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_colonies_0160126_'
  
  # Load data 
  colonyData <- read.csv('/Users/paudelbb/Downloads/rajpaper/dentistData/WM9_colonies_20160126.txt')
  #gapdhNormData <- gapdhNormalizeData(colonyData, minGapdh=50)
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(colonyData)[4:22],
                                  threshold=c(10,20,20,20, #EGFR,SOX10,CCNA2,HAPDH
                                              10,15,15,50, #WNT5A,PDGFRB,PDGFC,SERPINE1
                                              20,15,10,1000, #NGFR,NRG1,FOSL1,VEGFC
                                              15,10,20,1000, #AXL,MITF,LOXL2,RUNX2
                                              20,25,10)) #FGFR1,JUN,VGF
  
  thresholds <- data.frame(geneName=colnames(colonyData)[4:22],
                           threshold=rep(0,19))
  gapdhThresholds <- data.frame(geneName=colnames(colonyData)[4:22],
                                threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(colonyData[,i+3],1-percentileForThresholds)
    #gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {
      thresholds$threshold[i] <- percentThresh
    } 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  # For the non-jackpot genes, I want to override the percentiles and set a manual threshold - 
  # We just want to pick something that will give us all the "high" cells:
  
  # These were selected based upon the commented plot
  # ggplot(colonyData,aes(x=SOX10))+geom_histogram() + geom_vline(xintercept=150)
  #thresholds$threshold[2] <- 150 #SOX10
  #ggplot(colonyData,aes(x=GAPDH))+geom_histogram() + geom_vline(xintercept=600)
  #thresholds$threshold[4] <- 600 #GAPDH
  
  
  #percentileForThresholds <- 0.02
  #ggplot(gapdhNormData,aes(x=MITF))+geom_histogram() + 
  #  geom_vline(xintercept=quantile(gapdhNormData$MITF,1-percentileForThresholds))
  
#   gapdhThresholds$threshold[7] <- 1
#   gapdhThresholds$threshold[11] <- 1
#   gapdhThresholds$threshold[16] <- 1 # our RUNX2 signal is spotty throughout.
  #thresholds$gapdhThreshold[]
  
  #WM9_colonies_20151006 <- list(plotName,plotDir,colonyData,thresholds,gapdhThresholds)
  WM9_colonies_20160126 <- list(plotName,plotDir,colonyData,thresholds)
  return(WM9_colonies_20160126)
  
}

## notes from google docs.
# 20160222_WM9_colony data
# hyb 1
# EGFR - minimum threshold 10
# 
# hyb2
# WNT5A - minimum 10
# PDGFRB - minimum 15
# SERPINE1 - minimum 50 (only 1 cell above this threshold)
# PDGFC - 15
# 
# hyb3 
# NGFR - minimum 20
# NRG1 - minimum 15
# VEGFC - did not see anything with real signal
# FOSL1 - threshold anywhere
# 
# hyb4
# AXL - 15 
# MITF - threshold anywhere
# LOXL2 - 20
# RUNX2 - nothing
# 
# hyb5
# FGFR1 - 20
# VGF - threshold anywhere
# JUN - 25



