# parameters file for WM9 1week 20150821
# cleaned by Maggie

load_WM9_1week_20150821 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_1week_20150821_'
  
  # Load data 
  data <- read.csv('/Users/paudelbb/Downloads/rajpaper/dentistData/WM9_1week_20150821.txt')
  #gapdhNormData <- gapdhNormalizeData(data, minGapdh=50)
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(data)[4:22],
                                  threshold=c(10,#EGFR
                                              0,#SOX10 - threshold anywhere
                                              100,#CCNA2 - no spots
                                              0,#GAPDH - threshold anywhere
                                              29,# Maggie's notes indicate no spots.
                                              21,#PDGFRB - Maggie's notes indicate no spots
                                              100,#PDGFC - no spots
                                              20,#SERPINE1 - no spots according to Maggie's notes
                                              30,#NGFR 
                                              50,#NRG1 - seems high, may need to clean further. 
                                              100,#FOSL1 - no spots
                                              15,#VEGFC 
                                              10,#AXL
                                              10,#MITF - threshold anywhere
                                              100,#LOXL2 - no spots according to Maggie's notes
                                              10,#RUNX2 -  no spots according to Maggie's notes
                                              10,#FGFR1
                                              45,#JUN - seems high, may need to clean further. 
                                              100)) #VGF - no spots
  
  thresholds <- data.frame(geneName=colnames(data)[4:22],threshold=rep(0,19))
  #gapdhThresholds <- data.frame(geneName=colnames(data)[4:22],
  #threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(data[,i+3],1-percentileForThresholds)
    #gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {thresholds$threshold[i] <- percentThresh} 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  
  
  WM9_1week_20150821 <- list(plotName,plotDir,data,thresholds)
  return(WM9_1week_20150821)
}

## Maggie's notes
# 20150821_WM9_week1Drug_ReplicateTimecourse
# 
# Hyb1_take2
# alexa- Cleaned down through 7, min thresh = 7
# cy - tons of super bright background spots, no legit spots
# nir - checked down to 400, looks good, can probably threshold anywhere
# tmr- checked down to 600, looks good, threshold anywhere
# Hyb 2 _ take 2
# Alexa - no legit spots
# cy- still the bright background spot issue. No legit spots. 
# nir- no legit spots
# tmr - no legit spots
# Hyb3_
# Alexa - checked down to 30 spots. min thresh = 30 some spots assigned wrong
# Cy - no legit spots
# nir - checked down to 15, min thresh = 15
# tmr - checked down to 50. min thresh = 50
# 
# Hyb 4 
# Alexa - checked down to 51 spots, looks pretty good, can probably threshold anywhere
# cy-          no legit spots
# nir-  no legit spots
# tmr- checked down to 68, a lot of cells are actually multiple cells called as 1. I cut some out but not all. 
# Hyb 5
# alexa - checked down to 40, mostly good. Safe threshold = 40 but can probably go lower.
# cy - no legit spots
# tmr - cleaned down to 45, min thresh= 45



