# parameters file for WM9 no drug 20150810

load_WM9_noDrug_20150810 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_noDrug_20150810_'
  
  # Load data 
  noDrugData <- read.csv('/Users/paudelbb/Downloads/rajpaper/dentistData/WM9_noDrug_20150810.txt')
  gapdhNormData <- gapdhNormalizeData(noDrugData, minGapdh=50)
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(noDrugData)[4:22],
                                  threshold=c(10,20,20,20,15,5,10,20,20,10,10,10,10,10,10,10,5,10,10))
  
  thresholds <- data.frame(geneName=colnames(noDrugData)[4:22],
                           threshold=rep(0,19))
  gapdhThresholds <- data.frame(geneName=colnames(noDrugData)[4:22],
                                threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(noDrugData[,i+3],1-percentileForThresholds)
    gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {
      thresholds$threshold[i] <- percentThresh
      } 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  # For the non-jackpot genes, I want to override the percentiles and set a manual threshold - 
  # We just want to pick something that will give us all the "high" cells:
  
  # These were selected based upon the commented plot
  # ggplot(noDrugData,aes(x=SOX10))+geom_histogram() + geom_vline(xintercept=200)
  thresholds$threshold[2] <- 150 #SOX10
  #ggplot(noDrugData,aes(x=GAPDH))+geom_histogram() + geom_vline(xintercept=750)
  thresholds$threshold[4] <- 750 #GAPDH
  #ggplot(noDrugData,aes(x=CCNA2))+geom_histogram() + geom_vline(xintercept=25)
  thresholds$threshold[3] <- 25
  #ggplot(noDrugData,aes(x=MITF))+geom_histogram() + geom_vline(xintercept=90)
  thresholds$threshold[14] <- 120
  
  
  #percentileForThresholds <- 0.02
  #ggplot(gapdhNormData,aes(x=MITF))+geom_histogram() + 
  #  geom_vline(xintercept=quantile(gapdhNormData$MITF,1-percentileForThresholds))
  
  gapdhThresholds$threshold[7] <- 1
  gapdhThresholds$threshold[11] <- 1
  #thresholds$gapdhThreshold[]
  
  WM9_noDrug_20150810 <- list(plotName,plotDir,noDrugData,thresholds,gapdhThresholds)
  return(WM9_noDrug_20150810)
  
}

