# parameters file for WM9 colonies 10/06/2015

load_WM9_colonies_20151006 <- function(percentileForThresholds){
  # define directories
  plotDir <- plotDir
  
  # this will be the begining of the name for every plot generated by this script
  plotName <- 'WM9_colonies_20151006_'
  
  # Load data 
  colonyData <- read.csv('dentistData/WM9_colonies_20151006.txt')
  gapdhNormData <- gapdhNormalizeData(colonyData, minGapdh=50)
  
  # Load thresholds 
  # We have a minimum threshold based upon how far we cleaned up the data:
  thresholdsMinimum <- data.frame(geneName=colnames(colonyData)[4:22],
                                  threshold=c(10,20,20,20,15,15,3,30,10,10,10,20,20,10,25,1000,20,30,10))
  # I updated these based upon my notes from cleaning - SMS 1/6/15
  
  thresholds <- data.frame(geneName=colnames(colonyData)[4:22],
                           threshold=rep(0,19))
  gapdhThresholds <- data.frame(geneName=colnames(colonyData)[4:22],
                                threshold=rep(0,19))
  for (i in 1:dim(thresholds)[1]){
    percentThresh <- quantile(colonyData[,i+3],1-percentileForThresholds)
    gapdhThresholds$threshold[i] <- quantile(gapdhNormData[,i+3],1-percentileForThresholds)
    if (percentThresh>= thresholdsMinimum$threshold[i]) {
      thresholds$threshold[i] <- percentThresh
    } 
    else {thresholds$threshold[i] <- thresholdsMinimum$threshold[i]}
  }
  
  # For the non-jackpot genes, I want to override the percentiles and set a manual threshold - 
  # We just want to pick something that will give us all the "high" cells:
  
  # These were selected based upon the commented plot
  # ggplot(colonyData,aes(x=SOX10))+geom_histogram() + geom_vline(xintercept=150)
  thresholds$threshold[2] <- 150 #SOX10
  #ggplot(colonyData,aes(x=GAPDH))+geom_histogram() + geom_vline(xintercept=600)
  thresholds$threshold[4] <- 600 #GAPDH
  
  
  #percentileForThresholds <- 0.02
  #ggplot(gapdhNormData,aes(x=MITF))+geom_histogram() + 
  #  geom_vline(xintercept=quantile(gapdhNormData$MITF,1-percentileForThresholds))
  
  gapdhThresholds$threshold[7] <- 1
  gapdhThresholds$threshold[11] <- 1
  gapdhThresholds$threshold[16] <- 1 # our RUNX2 signal is spotty throughout.
  #thresholds$gapdhThreshold[]
  
  WM9_colonies_20151006 <- list(plotName,plotDir,colonyData,thresholds,gapdhThresholds)
  return(WM9_colonies_20151006)
  
}

## notes from google docs.
# 20151006_WM9_colonies
# **processed by Sydney**
#   Hyb 1
# EGFR - Alexa - minimum 10
# SOX10 - Cy3 - Fine
# GAPDH - Atto700 - Fine
# CCNA2 - Atto647n - Fine
# Hyb 2 
# WNT5A - Alexa - minimum 15
# PDGFRB - Cy3 - minimum 15
# SERPINE1 - Atto700 - minimum 30
# PDGFC - Atto647n - minimum 2-3
# Hyb 3 
# NGFR - Alexa - minimum 10 
# NRG1 - Cy3 - minimum 10
# VEGFC - Atto700 - minimum 20
# FOSL1 - looks great - no minimum
# Hyb 4 
# LOXL2 - Atto647n - minimum 25
# AXL - Alexa - minimum 20 
# RUNX2 - Atto700 - we have some signal, but it is kinda messed up. For example, it will look great in one image plane, but then the next plane over will look blurry and weird.
# MITF - no minimum
# Hyb 5
# FGFR1 - Alexa - minimum 20 
# JUN - Cy3 - minimum 30
# VGF - signal looks good throughout.


